# Generated by Django 4.2.14 on 2024-07-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email_id", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_no", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "job_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("prod_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TV_LCD", "TV (LCD)"),
                            ("TV_LED", "TV (LED)"),
                            ("TV_PLASMA", "TV (PLASMA)"),
                            ("TV_CRT", "TV (CRT)"),
                            ("AMPLIFIERS", "Amplifiers"),
                            ("SPEAKERS", "Speakers"),
                            ("PROJECTORS", "Projectors"),
                            ("MICROPHONE", "Microphone"),
                            ("MIXERS", "Mixers"),
                            ("TURN_TABLES", "Turn Tables"),
                            ("HEADPHONES", "Headphones"),
                            ("PC", "PC"),
                            ("SMART_DEVICE", "Smart Device"),
                            ("REMOTES", "Remotes"),
                            ("GAMING_CONSOLES", "Gaming Consoles"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=50)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("URGENT", "Urgent"),
                            ("HIGH_PRIORITY", "High Priority"),
                            ("LOW_PRIORITY", "Low Priority"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GOING_ON", "Going On"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.clients"
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.products"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_description", models.TextField()),
                ("work_hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prod_name", models.CharField(blank=True, max_length=255)),
                ("prod_description", models.TextField(blank=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_services",
                        to="base.products",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clients",
            name="job_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.products"
            ),
        ),
    ]
