# Generated by Django 4.2.14 on 2024-07-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="job_id",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.products",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="client_id",
            field=models.ForeignKey(
                db_column="client_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.clients",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="job_id",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.products",
            ),
        ),
    ]
