# Generated by Django 4.2.14 on 2024-07-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_clients_job_id_alter_services_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
