# Generated by Django 4.2.14 on 2024-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_services_service_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="service_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
