# Generated by Django 4.2.14 on 2024-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_services_service_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="client_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
