# Generated by Django 4.2.14 on 2024-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_clients_client_id_alter_services_service_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postservices", name="work_hours", field=models.IntegerField(),
        ),
    ]
